# Generated by Django 4.1.3 on 2022-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('S_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
