# Generated by Django 4.1.3 on 2022-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
