# Generated by Django 4.1.3 on 2022-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
